---
title: "Preprocessing"
author: "Linfeng Hu"
date: "2024-02-20"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Datasets
```{r}
folder_path <- "/Users/linfenghu/Desktop/SAMHSA_rdata"
rdata_files <- list.files(folder_path, pattern = "\\.rdata$", full.names = TRUE)
for (file in rdata_files) {load(file)}
```

## Aggregate based on STATE
```{r}
#dataset %>% group_by(STATEFIP) %>% 
library(purrr)
library(forcats)
library(haven)
library(dplyr)
library(tidyr)
aggregate_dataset <- function(dataset) {
  labelled_columns <- names(dataset)[sapply(dataset, is.labelled)]
  dataset[labelled_columns] <- lapply(dataset[labelled_columns], as.integer)
  
  aggregated_data <- dataset %>%
    group_by(STATEFIP) %>%
    summarize(
      YEAR = first(YEAR),  # Keep the first value of YEAR
      POPULATION = n(),
      SPHSERVICE = sum(SPHSERVICE == 1, na.rm = TRUE),  
      CMPSERVICE = sum(CMPSERVICE == 1, na.rm = TRUE),
      OPISERVICE = sum(OPISERVICE == 1, na.rm = TRUE),  
      RTCSERVICE = sum(RTCSERVICE == 1, na.rm = TRUE),  
      IJSSERVICE = sum(IJSSERVICE == 1, na.rm = TRUE),  
      MH1_values = list(table(factor(MH1, levels = c(-9,1:13))))
    ) %>%
    ungroup() %>%
    mutate(MH1_values = map(MH1_values, ~setNames(as.list(.x), paste0(names(.x))))) %>%
    unnest_wider(MH1_values, names_sep = "_") %>%
    replace(is.na(.), 0)  # Replace NA values with 0
  return(aggregated_data)
}
```

```{r}
# Apply the aggregation function to each dataset
df_2013 <- aggregate_dataset(mhcld_puf_2013_r)
df_2014 <- aggregate_dataset(mhcld_puf_2014_r)
df_2015 <- aggregate_dataset(mhcld_puf_2015_r)
df_2016 <- aggregate_dataset(mhcld_puf_2016_r)
df_2017 <- aggregate_dataset(mhcld_puf_2017_r)
df_2018 <- aggregate_dataset(mhcld_puf_2018_r)
df_2019 <- aggregate_dataset(mhcld_puf_2019_r)
df_2020 <- aggregate_dataset(mhcld_puf_2020_r)
df_2021 <- aggregate_dataset(mhcld_puf_2021_r)
```

```{r}
df_list <- list(df_2013, df_2014, df_2015, df_2016, df_2017, df_2018, df_2019, df_2020, df_2021)
stacked_df <- bind_rows(df_list)
write.csv(stacked_df, "stacked_data_state.csv", row.names = FALSE)
```

## Merge all dataframes based on STATE
```{r}
add_year_to_columns <- function(df, year) {
  rename_cols <- setdiff(names(df), c("YEAR", "STATEFIP"))
  new_names <- paste0(rename_cols, "_", year)
  names(df)[names(df) %in% rename_cols] <- new_names
  return(df)
}

remove_year_column <- function(df) {
  df <- df[, !names(df) %in% c("YEAR")]
  return(df)
}
df_list <- list(df_2013, df_2014, df_2015, df_2016, df_2017, df_2018, df_2019, df_2020, df_2021)
years <- c(2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021)
for (i in seq_along(df_list)) {
  df_list[[i]] <- add_year_to_columns(df_list[[i]], years[i])
  df_list[[i]] <- remove_year_column(df_list[[i]])
}
merged_df <- Reduce(function(x, y) merge(x, y, by = "STATEFIP", all = TRUE), df_list)
write.csv(merged_df, "merged_data_state.csv", row.names = FALSE)
```




## Aggregate based on DIAGNOSIS
```{r}
aggregate_dataset_Diagnosis <- function(dataset) {
  result <- dataset %>%
    group_by(YEAR, MH1) %>%
    summarise(
      Male = mean(GENDER == 1, na.rm = TRUE),
      SpecialEdu = mean(EDUC == 1, na.rm = TRUE),
      Edu8 = mean(EDUC == 2, na.rm = TRUE),
      Edu12 = mean(EDUC == 3 | EDUC == 4, na.rm = TRUE),
      EduHigh = mean(EDUC == 5, na.rm = TRUE),
      Black = mean(RACE == 3, na.rm = TRUE),
      White = mean(RACE == 5, na.rm = TRUE),
      OtherRace = mean(RACE %in% c(1,2,4,6), na.rm = TRUE),
      NeverMarried = mean(MARSTAT == 1, na.rm = TRUE),
      NeverMarried = mean(MARSTAT == 1, na.rm = TRUE),
      MarriageHistory = mean(MARSTAT %in% c(2,3,4), na.rm = TRUE),
      NotSMISED = mean(SMISED == 3, na.rm = TRUE),
      SAP = mean(SAP == 1, na.rm = TRUE),
      PrivateResidence = mean(LIVARAG == 2, na.rm = TRUE)
      )
}
```

```{r}
df_2013 <- aggregate_dataset_Diagnosis(mhcld_puf_2013_r)
df_2014 <- aggregate_dataset_Diagnosis(mhcld_puf_2014_r)
df_2015 <- aggregate_dataset_Diagnosis(mhcld_puf_2015_r)
df_2016 <- aggregate_dataset_Diagnosis(mhcld_puf_2016_r)
df_2017 <- aggregate_dataset_Diagnosis(mhcld_puf_2017_r)
df_2018 <- aggregate_dataset_Diagnosis(mhcld_puf_2018_r)
df_2019 <- aggregate_dataset_Diagnosis(mhcld_puf_2019_r)
df_2020 <- aggregate_dataset_Diagnosis(mhcld_puf_2020_r)
df_2021 <- aggregate_dataset_Diagnosis(mhcld_puf_2021_r)
```
```{r}
df_list <- list(df_2013, df_2014, df_2015, df_2016, df_2017, df_2018, df_2019, df_2020, df_2021)
stacked_df <- bind_rows(df_list)
write.csv(stacked_df, "merged_data_diagnosis.csv", row.names = FALSE)
```

